[Design] 계정 로그인 뷰 구현
TeamFair/ILSANG-iOS pull request #33
Opened 2024-06-07 10:52 UTC by HIBAR97

#### close #31

### ✏️ 개요
로그인 뷰 구현, 테스트 버튼 구현

### 💻 작업 사항
로그인 뷰에 필요한 에셋 추가, 로그인 기능 구현

### 📄 리뷰 노트
테스트 로그인은 임시로 Bindding 변수를 통해 이동하도록 작성하였습니다.
추후 API가 만들어지면 수정해야합니다.

### 📱결과 화면(optional)
<img src = "https://github.com/TeamFair/ILSANG-iOS/assets/96377739/d8d26c04-2b2c-417f-9aba-185adf888e98" width = "300">

2024-06-07 11:16 UTC, JINi0S requested changes

2024-06-07 11:16 UTC, JINi0S commented on ILSANG/Sources/Global/Model/LoginButton.swift
> +    }
이부분 정의한 거를 사용하는 부분에서는 빠져있네요!
피그마 보니까 폰트를 다 프리텐다드 사용하는 걸로 되어있어서 다시 확인해주시면 좋을 것 같습니다!

버튼의 corner radius 값도 피그마랑 다르게 되어있어서 이 부분도 같이 확인 부탁드립니다!!

2024-06-07 12:01 UTC, HIBAR97 commented on ILSANG/Sources/Global/Model/LoginButton.swift
> +    }
다른 곳에도 사용 될 수 있어서 폰트 추가 후, 이름 수정했습니다.

카카오, 구글, 애플로 로그인하기 버튼은 회사마다 각각 정해져있는 프리셋이 있고, 해당 디자인이 아니면 스토어 리젝 사유라서 폰트를 적용했습니다.

아래 링크 참고 하시면 좋을 것 같아요!
https://developers.kakao.com/docs/latest/ko/kakaologin/design-guide
https://developers.google.com/identity/branding-guidelines?hl=ko
https://developer.apple.com/design/human-interface-guidelines/sign-in-with-apple

버튼 Radius는 수정했습니다!

2024-06-08 03:50 UTC, JINi0S commented on ILSANG/Sources/Global/Model/LoginButton.swift
> +    }
링크 확인해봤는데 카카오에 지정하신 폰트는 내장되어있어서 파일을 따로 등록하지 않고, 
내장되어있는 폰트 이름으로 사용하도록 하면 리소스를 덜 낭비할 수 있을 것 같아요.

그리고 각 로그인 버튼 뷰 코드에서 폰트이름 작성한 부분도 LoginButton.fontname으로 가져다 쓸 수 있도록 하면 좋을 것 같습니다.

2024-06-08 04:14 UTC, HIBAR97 commented on ILSANG/Sources/Global/Model/LoginButton.swift
> +    }
> 링크 확인해봤는데 카카오에 지정하신 폰트는 내장되어있어서 파일을 따로 등록하지 않고, 내장되어있는 폰트 이름으로 사용하도록 하면 리소스를 덜 낭비할 수 있을 것 같아요.
> 
> 그리고 각 로그인 버튼 뷰 코드에서 폰트이름 작성한 부분도 LoginButton.fontname으로 가져다 쓸 수 있도록 하면 좋을 것 같습니다.

카카오 폰트 삭제후, LoginButton.fontname 연결했습니다.

2024-06-09 07:23 UTC, JINi0S commented on ILSANG/Sources/Global/Model/LoginButton.swift
> +    }
@HIBAR97 감사합니다!!

2024-06-09 07:24 UTC, JINi0S approved these changes

2024-06-09 07:51 UTC, merged