Feature/62 quest list api
TeamFair/ILSANG-iOS pull request #73
Opened 2024-07-04 08:00 UTC by HIBAR97

#### close #62 

### ✏️ 개요
퀘스트 목록 조회 API 연결

### 💻 작업 사항
- [x] 완료 퀘스트 목록 조회
- [x] 미완료 퀘스트 목록 조회

### 📄 리뷰 노트
Swagger에 표기 된 서버 200기준으로 작성하였습니다.
현재 서버 출력에 문제가 있어 데이터를 가져오지는 못합니다.

2024-07-04 08:36 UTC, JINi0S requested changes
변수명은 카멜케이스로 하는게 [swift](https://www.swift.org/documentation/api-design-guidelines/#naming)에서 권장하는 코드 작성 방식이에요 !
타입명이랑 변수명을 직관적으로 구분하고 파악하기 위해서, 수정되면 좋을 것 같습니다.

그리고 스웨거 확인했을 때 잘 응닶값 잘 보내주는 거 확인했는데, 어떤 부분 출력이 문제인지 공유해주실 수 있나요? 페이지 관련된 부분 말씀하시는 거면, 그 부분은 무시하고 필요한 응답값만 가져오도록 해주면 좋을 것 같습니다.

2024-07-04 08:36 UTC, JINi0S commented on ILSANG/Sources/Network/QuestNetwork.swift
> +    }
url 하나로 해도 될 것 같아 보이는데, 두개로 나누신 이유가 있을까요?

2024-07-04 08:36 UTC, JINi0S commented on ILSANG/Sources/Views/MyPage/MyPageView.swift
해당 뷰에서는 퀘스트 목록을 조회하는 것보단, 시간 필드가 필요해서 도전내역 조회 API를 요청하는 게 더 적절해보입니다.

2024-07-04 08:36 UTC, JINi0S commented on ILSANG/Sources/Views/MyPage/MyPageProfile.swift
> +    @StateObject var vm = MypageViewModel(userNetwork: UserNetwork(), questNetwork: <#QuestNetwork#>)
`<#QuestNetwork#>` 이 부분에서 에러 안나나요?

2024-07-05 01:11 UTC, HIBAR97 commented
> 그리고 스웨거 확인했을 때 잘 응닶값 잘 보내주는 거 확인했는데, 어떤 부분 출력이 문제인지 공유해주실 수 있나요? 페이지 관련된 부분 말씀하시는 거면, 그 부분은 무시하고 필요한 응답값만 가져오도록 해주면 좋을 것 같습니다.

원래 정상적인 응답은 아래와 같습니다.
> {
>   "size": 2,
>   "data": [
>     {
>       "questId": "QS00000001",
>       "marketId": "MK00000001",
>       "missionTitle": "TEA 5개(잔) 주문",
>       "rewardTitle": "COFFEE 80% 할인권",
>       "status": "PUBLISHED",
>       "expireDate": "2024-06-02 18:43:11"
>     },
>     {
>       "questId": "QS00000002",
>       "marketId": "MK00000001",
>       "missionTitle": "범죄도시4 보기",
>       "rewardTitle": "COFFEE 90% 할인권",
>       "status": "PUBLISHED",
>       "expireDate": null
>     }
>   ],
>   "total": 2,
>   "page": 0,
>   "status": "OK",
>   "message": "Your request has been processed successfully."
> }

현재 응답은 이렇습니다.

> {
>   "data": {
>     "content": [],
>     "pageable": {
>       "sort": {
>         "empty": true,
>         "sorted": false,
>         "unsorted": true
>       },
>       "offset": 0,
>       "pageNumber": 0,
>       "pageSize": 10,
>       "paged": true,
>       "unpaged": false
>     },
>     "totalElements": 0,
>     "totalPages": 0,
>     "last": true,
>     "size": 10,
>     "number": 0,
>     "sort": {
>       "empty": true,
>       "sorted": false,
>       "unsorted": true
>     },
>     "numberOfElements": 0,
>     "first": true,
>     "empty": true
>   },
>   "status": "OK",
>   "message": "Your request has been processed successfully."
> }

데이터의 형태가 아니라 완전 다른 내용을 출력하고 있어서 오류가 납니다.
같은 에러가 퀘스트, XP API에서 동일하게 발생하고 있습니다.

2024-07-05 01:13 UTC, HIBAR97 commented on ILSANG/Sources/Network/QuestNetwork.swift
> +    }
2개의 링크가 다릅니다. 
completedQuest와 uncompletedQuest를 각각 요청해야하는 상황이라 이렇게 만들었는데
좋은 방법이 있으면 알려주세요!

2024-07-05 01:17 UTC, HIBAR97 commented on ILSANG/Sources/Views/MyPage/MyPageProfile.swift
> +    @StateObject var vm = MypageViewModel(userNetwork: UserNetwork(), questNetwork: <#QuestNetwork#>)
오류는 나지 않는데 제가 누락했네요.
수정하겠습니다.

2024-07-05 06:31 UTC, HIBAR97 commented on ILSANG/Sources/Views/MyPage/MyPageView.swift
해당 API에도 expireDate가 존재하는데 도전내역이 더 맞을까요???

2024-07-05 06:37 UTC, JINi0S commented on ILSANG/Sources/Views/MyPage/MyPageView.swift
그 파라미터는 퀘스트 자체에 대한 만료일자여서 해당 뷰에는 적절하지 않습니다..!
퀘스트 조회 후 해당 퀘스트 id에 맞는 도전내역을 불러와도 되지만, 도전내역 조회에서 한 번에 받아오는 게 리소스 낭비가 덜 할 것 같습니다.

2024-07-05 06:39 UTC, JINi0S commented on ILSANG/Sources/Network/QuestNetwork.swift
> +    }
api의 링크가 다른 건 확인했는데, 앤디가 작성하신 부분에서 두 url 변수를 초기화하고 다른 값으로 다시 수정하는 부분은 없어보여서요.

2024-07-06 05:18 UTC, HIBAR97 commented on ILSANG/Sources/Network/QuestNetwork.swift
> +    }
MypageViewModel에 getQuest함수에 List에 추가하는 방법으로 구현했는데 잘 못된 부분이 있을까요??

2024-07-06 17:56 UTC, JINi0S commented on ILSANG/Sources/Network/QuestNetwork.swift
> +    }
@HIBAR97 
엇 그걸 얘기했던 건 아닙니다. url 변수를 두개로 구분해서 선언했는데, 지금 상태로는 하나만 있어도 문제 없어보여서요!-!
두개로 나눈 이유에 대해 언급하면 앤디가 한 번 생각해볼 수 있을 거라 생각했는데, 설명이 부족했나보네요 !

기존 코드로는 두 상태 모두 `uncompletedUrl` == `completedUrl` == `"http://000000:9090/api/customer/"`로 동일해서, 두 개로 나눈 장점을 잘 살리지 못하는 것 같아서 리뷰 남겼었어요! 
23, 29라인의 메서드 호출할 때 + 연산을 하는게 uncompletedUrl, completedUrl의 값을 변경하는 건 아니어서 초기화 상태 그대로이고, 값이 동일할텐데, 두 개로 나눈 이유가 있을까 싶어서요!

지금처럼 url이 두개로 나뉠때는 두가지 방법으로 구현해볼 수 있을 것 같아요 ‼️ 
각 장단점이 있을 것 같은데 고민해보시고 수정해주시면 좋을 것 같습니다.
url관련없는 부분은 일부 생략했습니다.!!

- url 2개로 나누는 방법
```swift 

    private let uncompletedUrl: String
    private let completedUrl: String

    init(uncompletedUrl: String = APIManager.makeURL(CustomerTarget(path: "uncompletedQuest")),
          completedUrl: String = APIManager.makeURL(CustomerTarget(path: "completedQuest"))) {
        self.uncompletedUrl = uncompletedUrl
        self.completedUrl = completedUrl
    }

    func getUncompletedQuest(page: Int) async -> Result<AWSQuest, Error> {
        return await Network.requestData(url: uncompletedUrl)
    }

    func getCompletedQuest(page: Int) async -> Result<AWSQuest, Error> {
        return await Network.requestData(url: completedUrl)
    }
``` 
- url 1개만 사용하는 방법
 ```swift 

    private let url: String

    init(url: String = APIManager.makeURL(CustomerTarget(path: ""))) {
        self.url = url
    }

    func getUncompletedQuest(page: Int) async -> Result<AWSQuest, Error> {
        return await Network.requestData(url: url+"uncompletedQuest")
    }

    func getCompletedQuest(page: Int) async -> Result<AWSQuest, Error> {
        return await Network.requestData(url: url+"completedQuest")
    }
```

2024-07-07 04:20 UTC, HIBAR97 commented on ILSANG/Sources/Network/QuestNetwork.swift
> +    }
아아 이렇게 말씀하시는거였군요.
이해했습니다.

2024-07-07 07:08 UTC, JINi0S approved these changes
@HIBAR97 
변경하신 부분 확인했습니다! 감사합니다 ! 👍🏻
quest, challenge 명칭 관련해서, 화면 연결 구현할 때는 더 명확하게 구분해서 사용하면 좋을 것 같습니다 !

2024-07-07 08:06 UTC, merged