[Feat] 경험치 API 연동
TeamFair/ILSANG-iOS pull request #82
Opened 2024-07-10 12:50 UTC by HIBAR97

#### close #74 

### ✏️ 개요
사용자 XP를 조회하고 레벨, 남은 경험치를 계산합니다.

### 💻 작업 사항
xp API 연동, 레벨, 남은 경험치 계산 함수 구현

### 📄 리뷰 노트
컨플릭트 해결하면서 오류가 있을 수 있습니다.

2024-07-11 05:42 UTC, JINi0S requested changes

2024-07-11 05:42 UTC, JINi0S commented on ILSANG/Sources/Model/Quest.swift
Quest.swift 파일이 두개여서, 실행하면 에러뜨길래 이 파일은 안쓰는 걸로 수정해둔게 저번 PR 이었습니다. #80 
다시 확인해보시고, 파일 삭제해주실 수 있나요?

2024-07-11 05:42 UTC, JINi0S commented on ILSANG/Sources/Views/MyPage/MyPageView.swift
> +    @State var questList: [Challenge]
MVVM으로 하기로 한 만큼 vm을 추가한 뷰에서는 뷰모델에 있는 변수를 사용하도록 해주세요,,

2024-07-11 05:42 UTC, JINi0S commented on ILSANG/Sources/Network/XPNetwork.swift
> +        let parameters: Parameters = ["userId": userId, "title": title,"page": page]
size를 빼도 동작하는 건 확인했습니다.

`func getXP(userId: String, title: String, page: Int, size: Int)`함수 파라미터에서는 size를 받는데, 
네트워크 요청하는 파라미터에는 지워둔 이유가 있을까요??

2024-07-11 05:42 UTC, JINi0S commented on ILSANG/Sources/Views/MyPage/MypageViewModel.swift
> +    @Published var questXp: [XP]?
XP 구조체가 이거던데, 이걸 배열로 가지고 있도록 하는게 의도하신 부분인가요??

``` swift
struct XP: Decodable {
    let content: XPContent
    let pageable: Int
    let status: String
    let message: String
}
```

2024-07-11 05:42 UTC, JINi0S commented on ILSANG/Sources/Views/MyPage/MypageViewModel.swift
> +    func getxpLog(userId: String, title: String, page: Int) async {
이걸 호출하는 부분은 없는데 추후에 하실건가요?

2024-07-11 05:42 UTC, JINi0S commented on ILSANG/Sources/Views/MyPage/MyPageProfile.swift
> +                ProfileImageView(profileImage: nil, level: vm.convertXPtoLv(XP: vm.userData?.xpPoint ?? 3))
피그마에 정의되어 있는 초기값 확인해서, 이 PR에서 같이 수정해주시면 좋을 것 같아요 !

2024-07-11 05:42 UTC, JINi0S commented on ILSANG/Sources/Views/MyPage/MyPageProfile.swift
> +                    Text("다음 레벨까지 \(vm.xpForNextLv(XP:  vm.userData?.xpPoint ?? 1300))XP 남았어요!")
이 부분도 초기값 확인해서 수정하면 어떨까요??

2024-07-11 07:02 UTC, HIBAR97 commented on ILSANG/Sources/Views/MyPage/MyPageView.swift
> +    @State var questList: [Challenge]
삭제하였습니다!

2024-07-11 07:06 UTC, HIBAR97 commented on ILSANG/Sources/Network/XPNetwork.swift
> +        let parameters: Parameters = ["userId": userId, "title": title,"page": page]
필요없다고 생각해서 삭제하였는데 누락된 부분입니다. 
삭제 조치하였습니다.

2024-07-11 07:14 UTC, HIBAR97 commented on ILSANG/Sources/Views/MyPage/MypageViewModel.swift
> +    @Published var questXp: [XP]?
넵 요청시 응답이 `"data": []` 배열 형태로 예상되어 이렇게 제작하였습니다. 

> {
>   "size": 10,
>   "data": [],
>   "total": 0,
>   "page": 0,
>   "status": "OK",
>   "message": "Your request has been processed successfully."
> }

1개의 데이터만 존재할 경우 `[XP] -> XP` 로 수정하도록 하겠습니다

2024-07-11 07:32 UTC, HIBAR97 commented on ILSANG/Sources/Views/MyPage/MypageViewModel.swift
> +    func getxpLog(userId: String, title: String, page: Int) async {
다음에 확인하려고 만들어두기만 했습니다.

2024-07-11 07:36 UTC, HIBAR97 commented on ILSANG/Sources/Views/MyPage/MyPageProfile.swift
> +                    Text("다음 레벨까지 \(vm.xpForNextLv(XP:  vm.userData?.xpPoint ?? 1300))XP 남았어요!")
두 개 전부 피그마 기준으로 수정했습니다.

2024-07-11 13:13 UTC, JINi0S commented on ILSANG/Sources/Views/MyPage/MyPageProfile.swift
> +                    Text("다음 레벨까지 \(vm.xpForNextLv(XP:  vm.userData?.xpPoint ?? 1300))XP 남았어요!")
<img width="792" alt="image" src="https://github.com/TeamFair/ILSANG-iOS/assets/100195563/2c3fe4fb-4665-49b4-a7c8-c04c47574cf0">


피그마 왼쪽에 있는 용어 정의에 작성되어있는 값들은 말한거였습니다,,,

2024-07-13 06:12 UTC, HIBAR97 commented on ILSANG/Sources/Views/MyPage/MyPageProfile.swift
> +                    Text("다음 레벨까지 \(vm.xpForNextLv(XP:  vm.userData?.xpPoint ?? 1300))XP 남았어요!")
수정했습니다!

2024-07-14 07:12 UTC, JINi0S approved these changes
확인했습니다 !

2024-07-14 07:12 UTC, JINi0S commented on ILSANG.xcodeproj/project.pbxproj
@HIBAR97 
여기 Quest.swift 파일 추가된 것도 같이 확인해주세요..
A1C6422B2C33F5C4004954CA 이 코드 잘 확인하셔서 지워주시고, SubmitAlertView 추가된 부분도 확인 부탁드려요.

2024-07-14 08:03 UTC, merged